//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Nullable<int> userID { get; set; }
        public Nullable<int> productID { get; set; }
        public string addedBy { get; set; }
        public int orderID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
